### PR TITLE
Add Krmfile and update kustomize to fix release-manifests generation

### LINKED ISSUE #28: "make release-manifests" no longer works
To run `clusterctl config cluster` locally, one must generate the `infrastructure-components.yaml` file which is done by `make release-manifests`, but this command currently prints the following error:
```
$ make release-manifests
release version v0.0.0
KUSTOMIZE_ENABLE_ALPHA_COMMANDS=true /tmp/test/cluster-api-provider-tink/hack/tools/bin/kustomize-v3.8.8 cfg set config image-tag v0.0.0
Error: unable to find "Krmfile" in package "config"
make: *** [Makefile:364: release-version] Error 1
```
CC @cpanato

### PR DESCRIPTION
**Pull request by invidian**
Closes #28

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

I'm not sure if this is the right fix for #28 though.

### CODE REVIEW

**Comment by cpanato** [comment]
you need to run the make generate to update all the things :)

**Comment by invidian** [comment]
I have doubts generated manifests with this fix are correct BTW.

**Comment by invidian** [comment]
Hm, given that this is caused by updating Kustomize to v3.8.8 and that manifests does not change, I think it should be fine to just add this file to fix #28.

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by detiber — APPROVED** [review]

**Pull request merged**
